CREATE TABLE "WO"."DETAIL_PAKET"
( "ID_DETAIL_PAKET" NUMBER(*,0) NOT NULL ENABLE,
"ID_PAKET" NUMBER(*,0),
"NAMA_ITEM_PAKET" VARCHAR2(150),
"JUMLAH_ITEM_PAKET" NUMBER(*,0),
CONSTRAINT "PK_DETAIL_PAKET" PRIMARY KEY ("ID_DETAIL_PAKET")
);