CREATE TABLE "WO"."PEMESANAN"
( "ID_PEMESANAN" NUMBER(*,0) NOT NULL ENABLE,
"TANGGAL_PEMESANAN" DATE,
"ID_CUSTOMER" NUMBER(*,0),
"ID_PAKET" NUMBER(*,0),
"TIPE_PEMBAYARAN" VARCHAR2(100),
"STATUS_PEMBAYARAN" VARCHAR2(100),
"TOTAL_PEMBAYARAN" NUMBER(11,2),
"DP_PEMBAYARAN" NUMBER(11,2),
CONSTRAINT "PK_PEMESANAN" PRIMARY KEY ("ID_PEMESANAN")
);